version: '2'

services:
  polis-participation:
    container_name: polis-participation
    build: .
    volumes:
      - .:/polisClientParticipation
    ports:
      - 5001:5001
    external_links:
      - polisserver_default
    networks:
      - default
      - polisserver_default

networks:
  polisserver_default:
    external: true
  



